---
title: "Untitled"
format: html
editor: visual
---

## SETUP

```{r}
library(haven)
library(tidyverse)
library(survival)
library(reshape2)
library(survminer)
library(cmprsk)
```

```{r}
dat <- read_dta("S:\\Project\\HealthierWomen\\Files\\SageFinalFiles\\Paper2CleanFile.dta")

variable.names(dat)
dat$perc <- 100*pnorm(dat$Z_1)

dat$mors_alder_cat <- cut(dat$MORS_ALDER_1, breaks = c(0, 19, 24, 29, 34, 9000))
dat$faarcat <- cut(dat$FAAR_1, breaks = c(0, 1979, 1989, 1999, 9000))

dat %>% group_by(mors_alder_cat) %>% count()

dat %>% group_by(faarcat) %>% count()


```



## GRAPHS

### FIGURE 2

```{r}

dat$comp <- str_c(dat$firstbirth, dat$quartile)
dat$comp <- relevel(as.factor(dat$comp), ref = "04")

fit <- coxph(Surv(time,ASCVD_T_69yrs) ~ comp + MUTD3C + mors_alder_cat + faarcat, data = dat)
summary(fit)

dazards <- data.frame(exp(fit$coefficients)) %>%  rownames_to_column("colname")
ci <- data.frame(exp(confint(fit))) %>% rownames_to_column("colname") %>% dplyr::select(-colname)
points <- bind_cols(dazards, ci)
print(points)

fake <- data.frame("comp04", 1.00, 1.00, 1.00)
names(fake) <- variable.names(points)

estimates <- rbind(points[1:3,], fake, points[4:15,])

estimates$firstbirth <- str_sub(estimates$colname, -2L, -2L)
estimates$quartile <- str_sub(estimates$colname, -1L)
estimates$gest <- c(rep("Term", 4),rep("Preterm", 4),rep("Term", 4),rep("Preterm", 4))
estimates$hdp <- c(rep(1, 8),rep(0, 8))


```


```{r}

ggplot(data = estimates)+
  geom_pointrange(aes(x = quartile, ymin = X2.5.., ymax = X97.5.., y = exp.fit.coefficients., shape = factor(hdp)), position = position_dodge(width = 0.2))+
  geom_line(aes(x = quartile, y = exp.fit.coefficients., group = factor(hdp)))+
  scale_y_log10()+
  facet_wrap(vars(gest))+
  theme_classic()+
  xlab("Quartiles of Birthweight")+
  ylab("HR (95%CI)")
  
ggsave("O:\\Export\\Figure1.png", plot = last_plot(), dpi = 500, width = 6, height = 3)
```

### FIGURE 1

```{r}
dat$opposite <- ifelse(dat$PRETERM_1 == 1, 0 ,1)

dat %>% 
  filter(Z_1 > -5) %>% filter(Z_1 < 5) %>% 
ggplot(aes(x = Z_1, linetype = factor(newprx_1)))+
  geom_density(alpha = 0.1, linewidth = 0.5)+
  theme_classic()+
  facet_wrap(vars(opposite))+
  ylab("Density")+
  xlab("Z-score")

ggsave("O:\\Export\\Curves.png", plot = last_plot(), dpi = 500, width = 6, height = 3)

```

### 

```{r}

fit <- coxph(Surv(time,ASCVD_T_69yrs) ~ PRETERM_1 + quartile + newprx_1 + PRETERM_1*quartile*newprx_1, data = dat)
summary(fit)

```

```{r}
library(broom)
fit <- coxph(Surv(time,ASCVD_T_69yrs) ~ factor(PRETERM_1) + factor(quartile) + factor(newprx_1) + factor(PRETERM_1)*factor(quartile)*factor(newprx_1), data = dat)
summary(fit)
tidy(fit)



```

### KAPLAN MEYER (from review)

```{r}

dat$z2c_1 <- ifelse(dat$Z_1 < 0, 1, 2)

dat$comp2c <- str_c(dat$firstbirth, dat$z2c_1)

model <- survfit(Surv(time,ASCVD_T_69yrs) ~ comp2c, data = dat)

ggsurvplot(model, data = dat, ylim = c(0.9, 1.0), palette = c("#440154FF", "#eeabfe", "#39568CFF", "#a6b8db", "#1F968BFF", "#cbf4ef", "#73D055FF", "#d6f1ce"), legend.labs = c("Term, Z < 0", "Term, Z >= 0", "Preterm, Z < 0", "Preterm, Z >= 0", "Term HDP, Z < 0", "Term HDP, Z >= 0", "Preterm HDP, Z < 0", "Preterm HDP, Z >= 0"))

```
